version: '3'
services:
  poc-auth-api-db:
    image: postgres:latest
    container_name: poc-auth-api
    environment:
      POSTGRES_USER: admin-monetario
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - poc-auth-api-volume:/var/lib/postgresql/data

volumes:
   poc-auth-api-volume: