spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monetario-auth-db
    username: admin-monetario
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 11a52682f93b5afbc7250cc38bfd0e1544b744a41334ce4347d60b6d6d675028
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
